---
title: "R Notebook"
output: html_notebook
---
```{r}
library(dplyr)
library(tidyverse)
```
# read in files using more complete quarterly data
```{r}
unemploymentNew = read.csv('../data/unrate_quarterly.csv')
inflationNew = read.csv('../data/pce_complete.csv') 
```

# rename columns in unemploymentNew
```{r}
unemploymentNew = unemploymentNew %>% 
              transmute(
              date = DATE,
              unemployment_rate = LRUNTTTTUSQ156S)
```
# rename columns in inflationNew
```{r}
inflationNew = inflationNew %>% 
              transmute(
              date = DATE,
              inflation_rate = DPCCRV1Q225SBEA)
```

#combine unemploymentInflation and inflationNew
```{r}
unemploymentandinflation <- merge(unemploymentNew, inflationNew) 
```

# graph unemployment and inflation using all available data
```{r}
ggplot(unemploymentandinflation, aes(x=unemployment_rate, y=inflation_rate)) + geom_point() + geom_point(color = "orange") + theme_bw() + ggtitle("Unemployment vs. Inflation from 1960 - Present") +
  theme(plot.title = element_text(hjust = 0.5)) + xlab("Unemployment Rate") + ylab("Inflation Rate")
```
# plot by 10-year periods
```{r}
ggplot(unemploymentandinflation[which(unemploymentandinflation$date>="1960-01-01" & unemploymentandinflation$date<="1969-10-01"),], aes(x=unemployment_rate, y=inflation_rate)) + geom_point() + geom_point(color = "orange") + theme_bw() + ggtitle("Unemployment vs. Inflation in the 1960's") +
  theme(plot.title = element_text(hjust = 0.5)) + xlab("Unemployment Rate") + ylab("Inflation Rate") 
```
```{r}
ggplot(unemploymentandinflation[which(unemploymentandinflation$date>="1970-01-01" & unemploymentandinflation$date<="1979-10-01"),], aes(x=unemployment_rate, y=inflation_rate)) + geom_point() + geom_point(color = "orange") + theme_bw() + ggtitle("Unemployment vs. Inflation in the 1970's") +
  theme(plot.title = element_text(hjust = 0.5)) + xlab("Unemployment Rate") + ylab("Inflation Rate") 
```
```{r}
ggplot(unemploymentandinflation[which(unemploymentandinflation$date>="1980-01-01" & unemploymentandinflation$date<="1989-10-01"),], aes(x=unemployment_rate, y=inflation_rate)) + geom_point() + geom_point(color = "orange") + theme_bw() + ggtitle("Unemployment vs. Inflation in the 1980's") +
  theme(plot.title = element_text(hjust = 0.5)) + xlab("Unemployment Rate") + ylab("Inflation Rate")
```
```{r}
ggplot(unemploymentandinflation[which(unemploymentandinflation$date>="1990-01-01" & unemploymentandinflation$date<="1999-10-01"),], aes(x=unemployment_rate, y=inflation_rate)) + geom_point() + geom_point(color = "orange") + theme_bw() + ggtitle("Unemployment vs. Inflation in the 1990's") +
  theme(plot.title = element_text(hjust = 0.5)) + xlab("Unemployment Rate") + ylab("Inflation Rate") 
```
```{r}
ggplot(unemploymentandinflation[which(unemploymentandinflation$date>="2000-01-01" & unemploymentandinflation$date<="2009-10-01"),], aes(x=unemployment_rate, y=inflation_rate)) + geom_point() + geom_point(color = "orange") + theme_bw() + ggtitle("Unemployment vs. Inflation in the early 2000's") +
  theme(plot.title = element_text(hjust = 0.5)) + xlab("Unemployment Rate") + ylab("Inflation Rate") 
```
```{r}
ggplot(unemploymentandinflation[which(unemploymentandinflation$date>="2010-01-01" & unemploymentandinflation$date<="2022-07-01"),], aes(x=unemployment_rate, y=inflation_rate)) + geom_point() + geom_point(color = "orange") + theme_bw() + ggtitle("Unemployment vs. Inflation since 2010") +
  theme(plot.title = element_text(hjust = 0.5)) + xlab("Unemployment Rate") + ylab("Inflation Rate") 
```
# plot by 5-year periods
```{r}
ggplot(unemploymentandinflation[which(unemploymentandinflation$date>="1960-01-01" & unemploymentandinflation$date<="1964-10-01"),], aes(x=unemployment_rate, y=inflation_rate)) + geom_point() + geom_point(color = "orange") + theme_bw() + ggtitle("Unemployment vs. Inflation 1960 - 1964") +
  theme(plot.title = element_text(hjust = 0.5)) + xlab("Unemployment Rate") + ylab("Inflation Rate") 
```
```{r}
ggplot(unemploymentandinflation[which(unemploymentandinflation$date>="1965-01-01" & unemploymentandinflation$date<="1969-10-01"),], aes(x=unemployment_rate, y=inflation_rate)) + geom_point() + geom_point(color = "orange") + theme_bw() + ggtitle("Unemployment vs. Inflation 1965 - 1969") +
  theme(plot.title = element_text(hjust = 0.5)) + xlab("Unemployment Rate") + ylab("Inflation Rate") 
```
```{r}
ggplot(unemploymentandinflation[which(unemploymentandinflation$date>="1970-01-01" & unemploymentandinflation$date<="1974-10-01"),], aes(x=unemployment_rate, y=inflation_rate)) + geom_point() + geom_point(color = "orange") + theme_bw() + ggtitle("Unemployment vs. Inflation 1970 - 1974") +
  theme(plot.title = element_text(hjust = 0.5)) + xlab("Unemployment Rate") + ylab("Inflation Rate") 
```
```{r}
ggplot(unemploymentandinflation[which(unemploymentandinflation$date>="1975-01-01" & unemploymentandinflation$date<="1979-10-01"),], aes(x=unemployment_rate, y=inflation_rate)) + geom_point() + geom_point(color = "orange") + theme_bw() + ggtitle("Unemployment vs. Inflation 1975 - 1979") +
  theme(plot.title = element_text(hjust = 0.5)) + xlab("Unemployment Rate") + ylab("Inflation Rate") 
```
```{r}
ggplot(unemploymentandinflation[which(unemploymentandinflation$date>="1980-01-01" & unemploymentandinflation$date<="1984-10-01"),], aes(x=unemployment_rate, y=inflation_rate)) + geom_point() + geom_point(color = "orange") + theme_bw() + ggtitle("Unemployment vs. Inflation 1980 - 1984") +
  theme(plot.title = element_text(hjust = 0.5)) + xlab("Unemployment Rate") + ylab("Inflation Rate") 
```
```{r}
ggplot(unemploymentandinflation[which(unemploymentandinflation$date>="1985-01-01" & unemploymentandinflation$date<="1989-10-01"),], aes(x=unemployment_rate, y=inflation_rate)) + geom_point() + geom_point(color = "orange") + theme_bw() + ggtitle("Unemployment vs. Inflation 1985 - 1989") +
  theme(plot.title = element_text(hjust = 0.5)) + xlab("Unemployment Rate") + ylab("Inflation Rate") 
```
```{r}
ggplot(unemploymentandinflation[which(unemploymentandinflation$date>="1990-01-01" & unemploymentandinflation$date<="1994-10-01"),], aes(x=unemployment_rate, y=inflation_rate)) + geom_point() + geom_point(color = "orange") + theme_bw() + ggtitle("Unemployment vs. Inflation 1990 - 1994") +
  theme(plot.title = element_text(hjust = 0.5)) + xlab("Unemployment Rate") + ylab("Inflation Rate") 
```
```{r}
ggplot(unemploymentandinflation[which(unemploymentandinflation$date>="1995-01-01" & unemploymentandinflation$date<="1999-10-01"),], aes(x=unemployment_rate, y=inflation_rate)) + geom_point() + geom_point(color = "orange") + theme_bw() + ggtitle("Unemployment vs. Inflation 1995 - 1999") +
  theme(plot.title = element_text(hjust = 0.5)) + xlab("Unemployment Rate") + ylab("Inflation Rate") 
```
```{r}
ggplot(unemploymentandinflation[which(unemploymentandinflation$date>="2000-01-01" & unemploymentandinflation$date<="2004-10-01"),], aes(x=unemployment_rate, y=inflation_rate)) + geom_point() + geom_point(color = "orange") + theme_bw() + ggtitle("Unemployment vs. Inflation 2000 - 2004") +
  theme(plot.title = element_text(hjust = 0.5)) + xlab("Unemployment Rate") + ylab("Inflation Rate") 
```
```{r}
ggplot(unemploymentandinflation[which(unemploymentandinflation$date>="2005-01-01" & unemploymentandinflation$date<="2009-10-01"),], aes(x=unemployment_rate, y=inflation_rate)) + geom_point() + geom_point(color = "orange") + theme_bw() + ggtitle("Unemployment vs. Inflation 2005 - 2009") +
  theme(plot.title = element_text(hjust = 0.5)) + xlab("Unemployment Rate") + ylab("Inflation Rate") 
```
```{r}
ggplot(unemploymentandinflation[which(unemploymentandinflation$date>="2010-01-01" & unemploymentandinflation$date<="2014-10-01"),], aes(x=unemployment_rate, y=inflation_rate)) + geom_point() + geom_point(color = "orange") + theme_bw() + ggtitle("Unemployment vs. Inflation 2010 - 2014") +
  theme(plot.title = element_text(hjust = 0.5)) + xlab("Unemployment Rate") + ylab("Inflation Rate") 
```
```{r}
ggplot(unemploymentandinflation[which(unemploymentandinflation$date>="2015-01-01" & unemploymentandinflation$date<="2022-07-01"),], aes(x=unemployment_rate, y=inflation_rate)) + geom_point() + geom_point(color = "orange") + theme_bw() + ggtitle("Unemployment vs. Inflation 2015 - 2022") +
  theme(plot.title = element_text(hjust = 0.5)) + xlab("Unemployment Rate") + ylab("Inflation Rate") 
```



